// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDZDxQZMSGtcp2uucQa7dOcvn7PmJNaCkE',
    appId: '1:417054168962:web:b98b4d5f878201df10219b',
    messagingSenderId: '417054168962',
    projectId: 'jumush-phone-otp',
    authDomain: 'jumush-phone-otp.firebaseapp.com',
    storageBucket: 'jumush-phone-otp.appspot.com',
    measurementId: 'G-GJ3GD1131F',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAdIDhQ_3JKxZ5qhzoTyNbSpvkBMjW8WwU',
    appId: '1:417054168962:android:16dd8251abf29ac910219b',
    messagingSenderId: '417054168962',
    projectId: 'jumush-phone-otp',
    storageBucket: 'jumush-phone-otp.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAB6a6ctaW3wDAZhbz4kjwfVqq7cPdDrlk',
    appId: '1:417054168962:ios:38ea9b8720ae510d10219b',
    messagingSenderId: '417054168962',
    projectId: 'jumush-phone-otp',
    storageBucket: 'jumush-phone-otp.appspot.com',
    iosClientId: '417054168962-49k6j2j03av1acaehjq27ok914imij09.apps.googleusercontent.com',
    iosBundleId: 'com.example.jumush',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAB6a6ctaW3wDAZhbz4kjwfVqq7cPdDrlk',
    appId: '1:417054168962:ios:38ea9b8720ae510d10219b',
    messagingSenderId: '417054168962',
    projectId: 'jumush-phone-otp',
    storageBucket: 'jumush-phone-otp.appspot.com',
    iosClientId: '417054168962-49k6j2j03av1acaehjq27ok914imij09.apps.googleusercontent.com',
    iosBundleId: 'com.example.jumush',
  );
}
